main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Vision"
    url: "#vision"
    weight: 2

  - name: "Services"
    url: "#Services"
    weight: 3

  # - name: "Pricing"
  #   url: "/#"
  #   weight: 4

  # - name: "Blog"
  #   url: "/blog"
  #   weight: 5

buttons:
  - name: "Book a call"
    url: "/#"
    weight: 5

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Vision"
    url: "#vision"
    weight: 2

  - name: "Services"
    url: "#services"
    weight: 3

  # - name: "Pricing"
  #   url: "/#"
  #   weight: 4

  # - name: "Blog"
  #   url: "/blog"
  #   weight: 5
